experiment_name: segmentation_v2
log_dir: ./experiments
epochs: 30
device: cuda:0
seed: 1

train:
  dataset:
    type: PlanetSegmentationDatasetV2
    params:
      csv_path: /datasets/rpartsey/satellite/planet/planet_dataset/train-val/random_split/train.csv
      transforms:
        image:
          ChannelsFirst:
            params: null
          ToNumpyInt32:
            params: null
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
          Normalize:
            params:
              mean:
                - 4417.258621276464
                - 3835.2537312971936
                - 3065.427994856266
                - 3783.5501700000373
                - 4417.258621276464
                - 3835.2537312971936
                - 3065.427994856266
                - 3783.5501700000373
              std:
                - 805.3352649209319
                - 752.9507977334065
                - 769.0657720493105
                - 1136.0581964787941
                - 805.3352649209319
                - 752.9507977334065
                - 769.0657720493105
                - 1136.0581964787941
        target:
          ChannelsFirst:
            params: null
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations:
        type: SmartCrop
        params:
          height: 256
          width: 256
          p: 1.0
  loader:
    type: DataLoader
    params:
      batch_size: 8
      num_workers: 2
      shuffle: True
      sampler: null

val:
  dataset:
    type: PlanetSegmentationDatasetV2
    params:
      csv_path: /datasets/rpartsey/satellite/planet/planet_dataset/train-val/random_split/val.csv
      transforms:
        image:
          ChannelsFirst:
            params: null
          ToNumpyInt32:
            params: null
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
          Normalize:
            params:
              mean:
                - 4417.258621276464
                - 3835.2537312971936
                - 3065.427994856266
                - 3783.5501700000373
                - 4417.258621276464
                - 3835.2537312971936
                - 3065.427994856266
                - 3783.5501700000373
              std:
                - 805.3352649209319
                - 752.9507977334065
                - 769.0657720493105
                - 1136.0581964787941
                - 805.3352649209319
                - 752.9507977334065
                - 769.0657720493105
                - 1136.0581964787941
        target:
          ChannelsFirst:
            params: null
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations:
        type: CenterCrop
        params:
          height: 256
          width: 256
          p: 1.0
  loader:
    type: DataLoader
    params:
      batch_size: 8
      num_workers: 2
      shuffle: False
      sampler: null

model:
  type: Unet
  save: True
  params:
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 8
    classes: 1
    activation: sigmoid

loss:
  type: BCELoss
  params: null

metrics:
  IoU:
    params:
      threshold: 0.5

optim:
  type: Adam
  params:
    lr: 0.0001

stopper:
  params:
    patience: 12
